### ISSUE TITLE
Empty table columns at the end should stay on same line 

### ISSUE THREAD

**Issue by lloydde** [tjchaplin/hammerdown#5]
ENV Mac / https://www.npmjs.org/package/hammerdown 0.0.18

REPO always
INPUT
```
<table>
    <tr>
      <td>
        <p>COLUMN1</p>
      </td>
      <td>
        <p>
          <code>COLUMN2</code>
        </p>
      </td>
      <td>
      </td>
    </tr>
</table>
```
ACTUAL
```
|COLUMN1|`COLUMN2`|
|
```
EXPECTED
`|COLUMN1|`COLUMN2`||`

**Comment by tjchaplin** [comment]
Thanks for opening the issue @lloydde.  I didn't see the open issue until yesterday.  Sorry for the late reply.

The problem was the empty td tag: <td></td>.  I have fixed this and will be pushed to npm shortly.  I have also added a test for this.

Thanks again for your help!
